[package]
name = "alloc-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
"raw_list" = { git = "https://github.com/GhostFire90/raw_list.git" }

[dev-dependencies]

[features]
default = ["std"]
std = []
